export { default as Header } from '@/components/header'
export { default as About } from '@/components/about'
export { default as Experience } from '@/components/experience'
export { default as Projects } from '@/components/projects'
export { default as Contact } from '@/components/contact'
export { default as Cursor } from '@/components/cursor'
export { default as ProjectsLoading } from '@/components/projects-loading'
export { default as Reveal } from '@/components/reveal'